group 'com.example.flutter_pangrowth'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }

        maven {
            url "https://artifact.bytedance.com/repository/Volcengine/"
        }

        maven {
            url "https://artifact.bytedance.com/repository/pangle/"
        }

        maven {
            url "https://artifact.bytedance.com/repository/AwemeOpenSDK"
        }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace "com.example.flutter_pangrowth"
    compileSdkVersion 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21
    }
}

configurations.all {
    //若接入流媒体sdk（小视频、直播）需要force constraint-layout版本
    resolutionStrategy {
        force 'com.android.support.constraint:constraint-layout:1.1.2'
    }
}

dependencies {
    api('com.google.code.gson:gson:2.13.1')
    api('com.squareup.okhttp3:okhttp:5.1.0')

    implementation ('com.blankj:utilcodex:1.31.1')

    //为保证兼容性 建议使用广告SDK版本
    implementation 'com.pangle.cn:ads-sdk-pro:7.0.2.9'
    implementation('com.pangle.cn:pangrowth-sdk:4.4.1.0') {
        exclude group: 'com.pangle.cn', module: 'partner-live-sdk'
        exclude group: 'com.pangle.cn', module: 'pangrowth-novel-sdk'
        exclude group: 'com.pangle.cn', module: 'pangrowth-game-sdk'
        exclude group: 'com.pangle.cn', module: 'pangrowth-luckycat-sdk'
        exclude group: 'com.pangle.cn', module: 'pangrowth-reward-sdk'
        exclude group: 'com.pangle.cn', module: 'partner-luckycat-api-sdk'
        exclude group: 'com.pangle.cn', module: 'pangrowth-luckycat-api'
    }
    implementation 'com.pangle.cn:pangrowth-base:2.9.0.4'
    implementation 'com.pangle.cn:pangrowth-djx-sdk-lite:2.9.0.4'
}
