/// 无后端：Api 仅作占位，所有方法返回默认值，不发起网络请求。
import 'package:base_object/models/FormModel/FormModel.dart';
import 'package:base_object/models/FormModel/LoginForm/LoginForm.dart';
import 'package:base_object/models/FormModel/appUpLoadForm/AppUpLoadForm.dart';
import 'package:base_object/models/FormModel/sendMobileCode/SendMobileCodeModel.dart';
import 'package:base_object/models/FormModel/upADForm/UpDataADForm.dart';
import 'package:base_object/models/FormModel/withdrawal/WithdrawalForm.dart';
import 'package:base_object/models/backModel/BackModel.dart';
import 'package:base_object/models/backModel/NoticeModel/NoticeModel.dart';
import 'package:base_object/models/backModel/TaskModel/TaskModel.dart';
import 'package:base_object/models/backModel/adTaskModel/AdTaskModel.dart';
import 'package:base_object/models/backModel/appUpLoadModel/AppUpLoadModel.dart';
import 'package:base_object/models/backModel/fKModelConfig/FKConfigVo.dart';
import 'package:base_object/models/backModel/loginModel/LoginModel.dart';
import 'package:base_object/models/backModel/newUserModel/NewUserModel.dart';
import 'package:base_object/models/backModel/rewarderModel/RewarderModel.dart';
import 'package:base_object/models/backModel/serviceModel/ServiceModel.dart';
import 'package:base_object/models/backModel/signModel/SignModel.dart';
import 'package:base_object/models/backModel/userModel/UserAmountListModel.dart';
import 'package:base_object/models/backModel/userModel/UserBayModel.dart';
import 'package:base_object/models/backModel/userModel/UserInviteCountModel.dart';
import 'package:base_object/models/backModel/userModel/UserInviteInfoModel.dart';
import 'package:base_object/models/backModel/userModel/UserInviteModel.dart';
import 'package:base_object/models/backModel/userModel/UserModel.dart';
import 'package:base_object/models/backModel/userModel/UserPayLModel.dart';
import 'package:base_object/models/backModel/userModel/UserSonModel.dart';
import 'package:base_object/models/backModel/userModel/UserTodayModel.dart';
import 'package:base_object/models/backModel/userModel/UserWithdrawalModel.dart';
import 'package:base_object/models/backModel/userModel/WithdrawalModel.dart';
import 'package:base_object/models/backModel/verifyCodeImgModel/VerifyCodeImgModel.dart';
import 'package:base_object/models/FormModel/checkDeviceForm/CheckDeviceForm.dart';
import 'package:get/get.dart';

class Api extends GetxService {
  static Api get to => Get.find<Api>();

  Future<AppUpLoadModel> postUpApp(AppUpLoadForm data) async => AppUpLoadModel();
  Future<NewUserModel> getNewcomerConfig() async => NewUserModel();
  Future<BackModel> getNewcomer() async => BackModel();
  Future<List<NoticeModel>> postNotice(FormModel data) async => [];
  Future<BackModel> postCheckIn() async => BackModel();
  Future<List<SignModel>> postSignList() async => [];
  Future<BackModel> postMinAdEnd() async => BackModel();
  Future<BackModel> postMinAdStart() async => BackModel();
  Future<AdTaskModel> postMinAdPrizeList(FormModel data) async => AdTaskModel();
  Future<List<TaskModel>> postTask(FormModel data) async => [];
  Future<List<ServiceModel>> getServerConfig(AppUpLoadForm form) async => [];
  Future<List<NoticeModel>> getNoticeAD() async => [];
  Future<List<NoticeModel>> getNoticeAPP() async => [];
  Future<VerifyCodeImgModel> postVerifyCodeImg() async => VerifyCodeImgModel();
  Future<BackModel> postSendMobileCode(SendMobileCodeModel data) async => BackModel();
  Future<BackModel> getVer(CheckDeviceForm checkDeviceForm) async => BackModel();
  Future<FKConfigVo> getFkConfig() async => FKConfigVo();
  Future<BackModel> getWithdrawalMoney(WithdrawalForm data) async => BackModel();
  Future<BackModel> getSetUser(LoginForm data) async => BackModel();
  Future<RewarderModel> getSelectAdV3() async => RewarderModel();
  Future<BackModel> getAdAmount() async => BackModel();
  Future<RewarderModel> getSelectAd(UpDataADForm data) async => RewarderModel();
  Future<BackModel> getBindInviteUser(LoginForm data) async => BackModel();
  Future<LoginModel> login(FormModel data) async => LoginModel();
  Future<BackModel> getInviteCode(FormModel data) async => BackModel();
  Future<UserModel> getUserInfo() async => UserModel();
  Future<UserTodayModel> getTodayAmount() async => UserTodayModel();
  Future<List<UserAmountListModel>> getUserAmountList() async => [];
  Future<List<UserAmountListModel>> getInviteAmountList() async => [];
  Future<List<UserWithdrawalModel>> getWithdrawalOrderList() async => [];
  Future<BackModel> getUpdateBindPay(WithdrawalForm data) async => BackModel();
  Future<BackModel> getRemoveBindPay(WithdrawalForm data) async => BackModel();
  Future<BackModel> getBindAlipay(WithdrawalForm data) async => BackModel();
  Future<List<UserPayLModel>> getPayList(FormModel data) async => [];
  Future<UserInviteCountModel> getInviteInfo() async => UserInviteCountModel();
  Future<List<WithdrawalModel>> getWithdrawalList() async => [];
  Future<List<UserInviteModel>> getInviteList() async => [];
  Future<UserInviteInfoModel> getMyInviteInfo() async => UserInviteInfoModel();
  Future<UserBayModel> getInviteMyBag() async => UserBayModel();
  Future<UserSonModel> getInviteMyInvite() async => UserSonModel();
}
